spring:
  datasource:
    url: jdbc:mysql://192.168.99.102:3306/sfg_dev
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
#this was a handy way to generate script for database schema creation. To prevent the script to be regenerate at any startup, we are commenting it
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql